### ISSUE TITLE
White screen on a Jolla C

### ISSUE THREAD

**Issue by dikonov** [otsaloma/pan-bikes#1]
Unable to run PanBikes in OS 2.2.0.29 on a Jolla C. It shows white screen after start and nothing happens until I cose the pan bikes app.

The same package runs OK on a Jolla 1, same OS version.  Please, check if the app handles the Jolla C screen resolution correctly.

**Comment by otsaloma** [comment]
I don't have a Jolla C to test, but I doubt this is a screen resolution issue. It would help of you could run the app via terminal (`sailfish-qml harbour-pan-bikes`) and copy any possible error output.

**Comment by dikonov** [comment]
It says 
```
Map unavailable
module "QtLocation" is not installed
      import QtLocation 5.0

```
Other mapping apps (Whogo maps, Poor maps, OSM maps) run without any issues on the same phone. Mapbox GL Native bindngs for Qt QML package from openrepos is installed.

**Comment by dikonov** [comment]
BTW, I have a Russian translation for the app, since it works in Moscow and Kazan at least.

**Comment by otsaloma** [comment]
It seems the RPM spec file is missing the QtLocation dependency. You can install it manually by doing

    devel-su
    pkcon refresh
    pkcon install qt5-qtdeclarative-import-location

**Comment by dikonov** [comment]
Now it shows a blank screen with shaded background and says 
`error: XDG_RUNTIME_DIR not set in the environment.`
After setting it to '/run/user/100000' (same as on Jolla1) the new error is 
`map.qml:25:1: QML Map: Plugin does not suport mapping.`
The geoservices provider is not supported.

**Comment by otsaloma** [comment]
You're probably trying to run it as root – don't do that. If you have a root terminal still open, hit Ctrl+D to exit or close the terminal and start anew.

**Comment by dikonov** [comment]
I did a full reboot and re-ran it as user. 

![20180702195600](https://user-images.githubusercontent.com/4271322/42176644-50c790f8-7e32-11e8-98e6-824d750d2771.jpg)

**Comment by otsaloma** [comment]
Sorry, in addition to QtLocation, the HERE plugin was missing. You need to install "qt5-plugin-geoservices-here" as well.
